<a href="https://colab.research.google.com/github/JordanMedinaOrtiz/mineria-datos/blob/main/Mineria_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos


##Primer Parcial


###Introducción

####Conceptos

La minería de datos (o data mining) es el proceso de analizar grandes volúmenes de datos para descubrir patrones, anomalías y correlaciones ocultas, transformando información cruda en conocimiento valioso para la toma de decisiones estratégicas, la predicción de tendencias y la optimización de procesos en diversas industrias.
En otras palabras la minería de datos es inteligencia aplicada a la información. Consiste en usar programas informáticos avanzados para revisar montañas de datos y encontrar "pistas" que un ser humano jamás vería por su cuenta. Su objetivo no es solo saber qué pasó ayer, sino adivinar qué pasará mañana (como qué comprará un cliente o si una transacción es falsa) para tomar decisiones más inteligentes y rentables.

La ciencia de datos es un campo multidisciplinario que usa métodos científicos, procesos, algoritmos y sistemas para extraer conocimiento e insights valiosos de grandes volúmenes de datos (Big Data), combinando estadística, matemáticas, inteligencia artificial (IA) e informática para analizar, predecir y tomar decisiones informadas, abarcando desde la obtención hasta la aplicación de la información.
En otras palabras ña ciencia de datos es el ecosistema completo del manejo de información. No es solo una técnica, es una disciplina híbrida que mezcla tres mundos:
Matemáticas y Estadística: Para modelar la realidad.
Programación y Tecnología: Para procesar lo masivo (Big Data).
Conocimiento del Negocio: Para que los resultados tengan sentido útil.
Su misión abarca todo el ciclo de vida del dato: desde que nace (captura), se limpia, se analiza, hasta que se convierte en un producto o una decisión ejecutiva.

####Ciencia de Datos

Help and Documentation in IPython


In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
L = [1, 2, 3]

In [ ]:
L.insert?

In [ ]:
L?

In [ ]:
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

IPython Magic Commands



In [2]:
# Sirve para evaluar el desempeño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

69.1 µs ± 869 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
# Con doble porcentaje podemos evaluar el desempeño
# de en cuanto tiempo de más de una línea de código
%%timeit
L = []
for n in range(10000):
  L.append(n ** 2)

813 µs ± 6.47 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


IPython and Shell Commands

In [5]:
!ls

sample_data


In [6]:
!pwd

/content


In [7]:
!echo "printing from the shell"

printing from the shell


In [8]:
contents = !ls

In [9]:
print(contents)

['sample_data']


In [10]:
directory = !pwd

In [11]:
print(directory)

['/content']


In [12]:
type(directory)

IPython.utils.text.SList

In [13]:
message = "hello from Python"

In [14]:
!echo {message}

hello from Python


In [16]:
%cd /content

/content


In [17]:
%ls

sample_data/


In [18]:
%cd sample_data/

/content/sample_data


In [19]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


Understanding Data Types in Python

In [21]:
# Importa numpy y renombralo como np
import numpy as np

In [22]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [24]:
# Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [25]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [27]:
# Cuando el argumento de np.array es una iteración anidada
# genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])