<a href="https://colab.research.google.com/github/JordanMedinaOrtiz/mineria-datos/blob/main/Mineria_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de Datos


##Primer Parcial


###Introducción

####Conceptos

La minería de datos (o data mining) es el proceso de analizar grandes volúmenes de datos para descubrir patrones, anomalías y correlaciones ocultas, transformando información cruda en conocimiento valioso para la toma de decisiones estratégicas, la predicción de tendencias y la optimización de procesos en diversas industrias.
En otras palabras la minería de datos es inteligencia aplicada a la información. Consiste en usar programas informáticos avanzados para revisar montañas de datos y encontrar "pistas" que un ser humano jamás vería por su cuenta. Su objetivo no es solo saber qué pasó ayer, sino adivinar qué pasará mañana (como qué comprará un cliente o si una transacción es falsa) para tomar decisiones más inteligentes y rentables.

La ciencia de datos es un campo multidisciplinario que usa métodos científicos, procesos, algoritmos y sistemas para extraer conocimiento e insights valiosos de grandes volúmenes de datos (Big Data), combinando estadística, matemáticas, inteligencia artificial (IA) e informática para analizar, predecir y tomar decisiones informadas, abarcando desde la obtención hasta la aplicación de la información.
En otras palabras ña ciencia de datos es el ecosistema completo del manejo de información. No es solo una técnica, es una disciplina híbrida que mezcla tres mundos:
Matemáticas y Estadística: Para modelar la realidad.
Programación y Tecnología: Para procesar lo masivo (Big Data).
Conocimiento del Negocio: Para que los resultados tengan sentido útil.
Su misión abarca todo el ciclo de vida del dato: desde que nace (captura), se limpia, se analiza, hasta que se convierte en un producto o una decisión ejecutiva.

####Ciencia de Datos

Help and Documentation in IPython


In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
L = [1, 2, 3]

In [ ]:
L.insert?

In [ ]:
L?

In [ ]:
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
len??

IPython Magic Commands



In [ ]:
# Sirve para evaluar el desempeño de una expresión en cuanto a tiempo
%timeit L = [n ** 2 for n in range(1000)]

69.1 µs ± 869 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# Con doble porcentaje podemos evaluar el desempeño
# de en cuanto tiempo de más de una línea de código
%%timeit
L = []
for n in range(10000):
  L.append(n ** 2)

813 µs ± 6.47 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
!pwd

/content


In [ ]:
!echo "printing from the shell"

printing from the shell


In [ ]:
contents = !ls

In [ ]:
print(contents)

['sample_data']


In [ ]:
directory = !pwd

In [ ]:
print(directory)

['/content']


In [ ]:
type(directory)

IPython.utils.text.SList

In [ ]:
message = "hello from Python"

In [ ]:
!echo {message}

hello from Python


In [ ]:
%cd /content

/content


In [ ]:
%ls

sample_data/


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


Understanding Data Types in Python

In [ ]:
# Importa numpy y renombralo como np
import numpy as np

In [ ]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
# Al ingresar enteros y flotantes los convierte en flotantes
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
# Cuando el argumento de np.array es una iteración anidada
# genera una matriz
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
import numpy as np

In [ ]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3, 3))

array([[0.06652152, 0.42526114, 0.45709022],
       [0.50508023, 0.52173454, 0.62776372],
       [0.32963255, 0.93711095, 0.20238419]])

In [ ]:
np.random.normal(0, 1, (3, 3))

array([[ 0.30682763, -0.27636963, -1.85993202],
       [ 0.53985631,  0.42718974,  1.47246459],
       [ 1.08526595,  0.21663762,  0.12226736]])

In [ ]:
np.random.randint(0, 10, (3, 3))

array([[9, 5, 6],
       [5, 2, 2],
       [7, 3, 8]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(3)

array([1., 1., 1.])

The Basics of NumPy Arrays

In [ ]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print("dtype:", x3.dtype)

dtype: int64


In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

np.int64(5)

In [ ]:
x1[4]

np.int64(7)

In [ ]:
x1[-2]

np.int64(7)

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[2, 0]

np.int64(1)

In [ ]:
x2[-1, -1] = 12
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7, 12]])

####Análisis Estadístico Básico con NumPy

Media (Mean)

In [ ]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [ ]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [ ]:
mediana = np.median(data)

print(mediana)

3.0


Varianza y Desviación Estándar

In [ ]:
varianza = np.var(data)
desviacion = np.std(data)

print(varianza)
print(desviacion)

2.0
1.4142135623730951


Generación de Datos Aleatorios

In [ ]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [ ]:
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]


####Cuadros Estadisticos

In [1]:
import numpy as np
import pandas as pd
from io import StringIO

raw = """Marca temporal\tNúmero de matrícula\t¿Cuántos años cumplidos tienes?\t¿Has realizado programas utilizando Python?\t¿Has utilizado Google Colab?\t¿Tienes cuenta de GitHub?
19/01/2026 18:32:18\t178920\t22\tSi\tNo\tSi
19/01/2026 18:32:23\t182712\t21\tSi\tNo\tSi
19/01/2026 18:32:25\t180370\t26\tSi\tSi\tSi
19/01/2026 18:32:27\t182570\t21\tSi\tSi\tSi
19/01/2026 18:32:28\t177622\t24\tSi\tNo\tSi
19/01/2026 18:32:29\t175166\t22\tSi\tSi\tSi
19/01/2026 18:32:30\t177573\t22\tSi\tSi\tSi
19/01/2026 18:32:35\t178430\t21\tSi\tSi\tSi
19/01/2026 18:32:38\t179169\t23\tSi\tNo\tSi
19/01/2026 18:32:41\t177263\t22\tSi\tSi\tSi
19/01/2026 18:32:48\t179884\t23\tSi\tNo\tSi
19/01/2026 18:32:48\t183016\t22\tSi\tNo\tSi
19/01/2026 18:32:50\t179033\t23\tSi\tSi\tNo
19/01/2026 18:32:54\t178218\t22\tSi\tNo\tSi
19/01/2026 18:32:55\t178446\t22\tSi\tSi\tSi
19/01/2026 18:33:00\t178166\t22\tSi\tSi\tNo
19/01/2026 18:33:02\t177406\t22\tSi\tNo\tSi
19/01/2026 18:33:05\t177192\t22\tSi\tSi\tSi
19/01/2026 18:33:08\t182451\t21\tSi\tNo\tSi
19/01/2026 18:33:08\t171513\t24\tNo\tNo\tSi
19/01/2026 18:33:09\t181619\t21\tSi\tNo\tSi
19/01/2026 18:33:12\t182298\t23\tSi\tNo\tSi
19/01/2026 18:33:14\t181419\t24\tNo\tNo\tSi
19/01/2026 18:33:32\t177291\t21\tSi\tSi\tSi
19/01/2026 18:33:42\t182085\t22\tSi\tNo\tSi
19/01/2026 18:33:53\t176453\t22\tSi\tNo\tSi
19/01/2026 18:34:04\t176263\t24\tSi\tNo\tSi
19/01/2026 18:34:06\t179997\t21\tSi\tNo\tSi
19/01/2026 18:36:21\t175842\t23\tSi\tNo\tNo
19/01/2026 20:19:21\t179913\t20\tSi\tNo\tSi
19/01/2026 20:19:48\t177301\t22\tSi\tSi\tNo
19/01/2026 20:20:06\t183060\t21\tSi\tNo\tSi
19/01/2026 20:20:08\t177935\t22\tSi\tSi\tSi
19/01/2026 20:20:19\t177700\t20\tSi\tSi\tSi
19/01/2026 20:20:26\t178318\t24\tSi\tSi\tSi
19/01/2026 20:20:27\t174653\t24\tSi\tNo\tSi
19/01/2026 20:20:29\t177139\t21\tSi\tNo\tSi
19/01/2026 20:20:31\t173479\t25\tSi\tNo\tNo
19/01/2026 20:20:39\t175588\t23\tNo\tNo\tSi
19/01/2026 20:20:45\t178774\t23\tSi\tSi\tSi
19/01/2026 20:20:45\t175031\t23\tSi\tNo\tNo
19/01/2026 20:20:49\t178396\t21\tSi\tSi\tSi
19/01/2026 20:20:49\t172068\t23\tNo\tNo\tNo
19/01/2026 20:20:50\t174197\t23\tNo\tNo\tSi
19/01/2026 20:20:55\t178584\t22\tSi\tNo\tSi
19/01/2026 20:20:55\t175329\t24\tSi\tNo\tSi
19/01/2026 20:20:56\t177685\t22\tSi\tSi\tSi
19/01/2026 20:20:57\t178678\t22\tNo\tNo\tSi
19/01/2026 20:21:04\t177143\t22\tSi\tNo\tSi
19/01/2026 20:21:07\t182318\t26\tSi\tNo\tSi
19/01/2026 20:21:27\t182377\t20\tSi\tNo\tSi
19/01/2026 20:21:34\t179419\t22\tSi\tNo\tNo
19/01/2026 20:21:35\t181662\t21\tSi\tNo\tSi
19/01/2026 20:21:38\t181760\t21\tSi\tNo\tSi
19/01/2026 20:22:06\t177888\t22\tSi\tNo\tSi
19/01/2026 20:22:15\t176535\t25\tSi\tNo\tSi
19/01/2026 20:22:29\t179862\t21\tSi\tNo\tSi
19/01/2026 20:22:32\t178378\t22\tSi\tNo\tSi
19/01/2026 20:22:50\t177451\t22\tSi\tNo\tSi
19/01/2026 20:23:15\t179804\t21\tSi\tNo\tSi
"""

# Cargar datos
df = pd.read_csv(StringIO(raw), sep='\t')
df.columns = [c.strip() for c in df.columns]

# Variables
df['edad'] = pd.to_numeric(df['¿Cuántos años cumplidos tienes?'], errors='coerce')
map_sn = {'Si': True, 'No': False}
df['prog_python'] = df['¿Has realizado programas utilizando Python?'].map(map_sn)
df['usa_colab'] = df['¿Has utilizado Google Colab?'].map(map_sn)
df['cuenta_github'] = df['¿Tienes cuenta de GitHub?'].map(map_sn)

In [3]:
df.head()

Marca temporal  Número de matrícula  ¿Cuántos años cumplidos tienes?  \
0  19/01/2026 18:32:18               178920                               22   
1  19/01/2026 18:32:23               182712                               21   
2  19/01/2026 18:32:25               180370                               26   
3  19/01/2026 18:32:27               182570                               21   
4  19/01/2026 18:32:28               177622                               24   

  ¿Has realizado programas utilizando Python? ¿Has utilizado Google Colab?  \
0                                          Si                           No   
1                                          Si                           No   
2                                          Si                           Si   
3                                          Si                           Si   
4                                          Si                           No   

  ¿Tienes cuenta de GitHub?  edad  prog_python  usa_colab  cuenta_github  
0                        Si    22         True      False           True  
1                        Si    21         True      False           True  
2                        Si    26         True       True           True  
3                        Si    21         True       True           True  
4                        Si    24         True      False           True

In [4]:
# A NumPy
edad = df['edad'].to_numpy(dtype=float)
prog_py = df['prog_python'].to_numpy(dtype=bool)
usa_colab = df['usa_colab'].to_numpy(dtype=bool)
cuenta_gh = df['cuenta_github'].to_numpy(dtype=bool)

In [6]:
print(f'ndarray edad primeros 5 elementos: {edad[:5]}')
print(f'ndarray prog_py primeros 5 elementos: {prog_py[:5]}')
print(f'ndarray usa_colab primeros 5 elementos: {usa_colab[:5]}')
print(f'ndarray cuenta_gh primeros 5 elementos: {cuenta_gh[:5]}')

ndarray edad primeros 5 elementos: [22. 21. 26. 21. 24.]
ndarray prog_py primeros 5 elementos: [ True  True  True  True  True]
ndarray usa_colab primeros 5 elementos: [False False  True  True False]
ndarray cuenta_gh primeros 5 elementos: [ True  True  True  True  True]


In [9]:
summary_age = {
    'n': int(edad.size),
    'min': float(np.min(edad)),
    'p25': float(np.percentile(edad, 25)),
    'mediana': float(np.median(edad)),
    'media': float(np.mean(edad)),
    'p75': float(np.percentile(edad, 75)),
    'max': float(np.max(edad)),
    'rango(ptp)': float(np.ptp(edad)),
    'var_muestral': float(np.var(edad, ddof=1)),
    'std_muestral': float(np.std(edad, ddof=1)),
    'cv': float(np.std(edad, ddof=1)/np.mean(edad)),
}

summary_age

{'n': 60,
 'min': 20.0,
 'p25': 21.0,
 'mediana': 22.0,
 'media': 22.3,
 'p75': 23.0,
 'max': 26.0,
 'rango(ptp)': 6.0,
 'var_muestral': 1.8406779661016948,
 'std_muestral': 1.3567158752302173,
 'cv': 0.06083927691615324}

In [10]:
# Frecuencias (NumPy)
freq_python = {'Si': int(np.count_nonzero(prog_py)), 'No': int(edad.size - np.count_nonzero(prog_py))}
freq_colab  = {'Si': int(np.count_nonzero(usa_colab)), 'No': int(edad.size - np.count_nonzero(usa_colab))}
freq_gh     = {'Si': int(np.count_nonzero(cuenta_gh)), 'No': int(edad.size - np.count_nonzero(cuenta_gh))}

print(f'Frecuencia de utilizar Python: {freq_python}')
print(f'Frecuencia de utilizar Google Colab: {freq_colab}')
print(f'Frecuencia de tener cuenta de GitHub: {freq_gh}')
#

Frecuencia de utilizar Python: {'Si': 54, 'No': 6}
Frecuencia de utilizar Google Colab: {'Si': 18, 'No': 42}
Frecuencia de tener cuenta de GitHub: {'Si': 52, 'No': 8}


In [12]:
def tabla2x2(a, b):
    t = np.zeros((2,2), dtype=int)
    t[1,1] = np.count_nonzero(a & b)
    t[1,0] = np.count_nonzero(a & ~b)
    t[0,1] = np.count_nonzero(~a & b)
    t[0,0] = np.count_nonzero(~a & ~b)
    return t

tab_py_colab = tabla2x2(prog_py, usa_colab)
tab_py_gh    = tabla2x2(prog_py, cuenta_gh)
tab_colab_gh = tabla2x2(usa_colab, cuenta_gh)

In [14]:
print(f'Tabla de contingencia de Python y Google Colab:\n{tab_py_colab}')
print(f'Tabla de contingencia de Python y GitHub:\n{tab_py_gh}')
print(f'Tabla de contingencia de Google Colab y GitHub:\n{tab_colab_gh}')

Tabla de contingencia de Python y Google Colab:
[[ 6  0]
 [36 18]]
Tabla de contingencia de Python y GitHub:
[[ 1  5]
 [ 7 47]]
Tabla de contingencia de Google Colab y GitHub:
[[ 5 37]
 [ 3 15]]
